name: ShilpiSharma
favicon: null
layout_spectrum: 0.36821424099616706
typography_spectrum: 0.986065881093964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6453022230416536
  lightness: 0.9255102586466819
  saturation: 0.06137606990523636
  rhythmicContrast: 0.7710551510099322
purpose: []
